### ISSUE TITLE
Overriding template path in update command

### ISSUE THREAD

**Issue by jamesrosling** [cruft/cruft#269]
Hi! 

I'm having some issues in getting the `cruft update` command to work for a repository that needs credentials to be included in the template url to enable the repository to be cloned. The command will be called through a Backstage action class rather than the cli. 

We're trying to use cruft to update project repos created with cruft, and the `cruft update` command is using the template url found in the .cruft.json file. We need to override this with the url containing auth credentials, as for security reasons this can't be a static value in the codebase. 

Is there a way to have an input parameter in `update` to allow us to pass a new template url, or some way to override this template url without doing our own implementation of the update step? 

Any help would be appreciated. 

Cheers

**Comment by f-repetto** [comment]
As a workaround in the `.cruft.json` file you can use a placeholder, e.g.:

```
{
  "template": "https://<PLACEHOLDER_TOKEN>@github.com/something-cookiecutter",
  "commit": "xxxxx",
 ...
```
In GH create a PAT with clone repo permissions. In the repo create a secret with PAT as the value e.g. `GH_CRUFT_TOKEN`

In the workflow file add an inject GH token into `.cruft.json` step:

```
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - name: Install Cruft
              run: pip3 install cruft

            - name: Inject GitHub Token into `.cruft.json`
              run: |
                sed -i 's|<PLACEHOLDER_TOKEN>|${{ secrets.GH_CRUFT_TOKEN }}|' .cruft.json
```
