### ISSUE TITLE
Structured files merge

### ISSUE THREAD

**Issue by koalp** [cruft/cruft#278]
Hello, I was wondering if cruft could have a way merge structured files. 

# Use case 

I have a `pyproject.toml` where I want to ignore updates for `tool.poetry.version`, merge `tool.poetry.dependencies` and overwrite configuration for my other tools (`tool.ruff`, `tool.mypy`, …) and for my dev and doc dependencies (`tool.poetry.group.dev.dependencies`, …) . Currently. I have to ignore pyproject.toml and update it manually.

# Proposal

Maybe some files could be merged (following rules) rather than overwritten : It would also allow to merge other structured files like yaml (I think to `.gitlab-ci.yaml` where I might want to keep steps that I added). 

**Example of configuration:**

``` toml
[tool.cruft]

# This would merge the whole file by overwriting existing keys and the one that have been added
[[tool.cruft.merge-file]]
file = ".gitlab-ci.yaml"

# This would merge the whole file except keys "tool.poetry.dependencies" and "tool.poetry.version"
[[tool.cruft.merge-file]]
file = "poetry.toml"
[[tool.cruft.merge-file.key]]
key = "tool.poetry.dependencies"
action = "ignore"
[[tool.cruft.merge-file.key]]
key = "tool.poetry.version"
action = "ignore"
```

---

I saw that there is a proposed issue and PR for regex ignore https://github.com/cruft/cruft/issues/250 that would also cover part of those issues.

---

Would this feature be accepted ?
I can try to write a PR if this feature interests you. If you think the feature is too specific, badly specified, too hard to implement or to maintain, I can close the issue.
